In [1]:
import pandas as pd

In [3]:
df =  pd.read_excel('../data/Nepal Basketball League 2019 Information.xlsx', sheet_name="Player Stat (MEN)")

df

,Nepal Basketball League 2019 (NBL) Player Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,Organised By,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Play For Deprived Children Nepal (PDCN),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stats Managed By Official Education Partner of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,S.NO,PLAYER NAME,JERSEY NO.,CLUB,Position,Height,Weight,NO. OF GAME PLAYED,TOTAL SCORE,AVR. SCORE PER GAME,...,FREE THROW ATTEMPT,FREE THROW MADE,FREE THROW ACCURACY %,EFFICIENCY,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Karma Gurung,8,GGIC,Shooting Guard,5'11,86,14,38,2.714286,...,12,6,50,2.071429,75.0,46.0,29.0,14.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,10,Binesh Neupane,12,RBC,PowerForward,6'0,85,14,24,1.714286,...,4,4,100,0.714286,45.0,35.0,10.0,14.0,NaN,NaN
126,11,Suman Basnet,13,RBC,Center,6'0,72,14,49,3.5,...,11,6,54.545455,4.928571,97.0,28.0,69.0,14.0,NaN,NaN
127,12,Rupak Kunwar,30,RBC,NaN,NaN,NaN,14,48,3.428571,...,8,4,50,0.785714,58.0,47.0,11.0,14.0,NaN,NaN
128,13,Anish Magar,5,RBC,NaN,NaN,NaN,14,47,3.357143,...,3,1,33.333333,2.642857,67.0,30.0,37.0,14.0,NaN,NaN
129,14,Asish Basnet,15,RBC,NaN,NaN,NaN,14,6,0.428571,...,1,1,100,0.214286,8.0,5.0,3.0,14.0,NaN,NaN

In [19]:
player_stats = [df.loc[4:16], df.loc[20:33], df.loc[36:49], df.loc[52:65], df.loc[68:81], df.loc[84:97], df.loc[100:113], df.loc[116:129]]

player_stats = pd.concat(player_stats)

In [20]:
player_stats.columns

Index(['Nepal Basketball League 2019 (NBL) Player Statistics', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38'],
      dtype='object')

In [21]:
player_stats.head()

,Nepal Basketball League 2019 (NBL) Player Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
4,1,Karma Gurung,8,GGIC,Shooting Guard,5'11,86,14,38,2.714286,...,12,6,50,2.071429,75.0,46.0,29.0,14.0,NaN,NaN
5,2,Chiranjivi Rokaya,35,GGIC,Small Forward,5'11,66,14,11,0.785714,...,8,1,12.5,0.571429,22.0,14.0,8.0,14.0,NaN,NaN
6,3,Rajiv Joshi,7,GGIC,Guard,5'10,76,14,112,8,...,22,18,81.818182,8,182.0,70.0,112.0,14.0,NaN,NaN
7,4,Binod Shrestha,3,GGIC,Gaurd,5'8,78,14,116,8.285714,...,6,4,66.666667,5.357143,161.0,86.0,75.0,14.0,NaN,NaN
8,5,Kabindra Pradhan,1,GGIC,Small Forward,6'0,69,14,41,2.928571,...,15,7,46.666667,3.571429,81.0,31.0,50.0,14.0,NaN,NaN

In [30]:
labels = df.iloc[3]
labels_dict = {}
for col in player_stats.columns:
    labels_dict[col] = labels[col]
    
labels_dict

{'Nepal Basketball League 2019 (NBL) Player Statistics': 'S.NO',
 'Unnamed: 1': 'PLAYER NAME',
 'Unnamed: 2': 'JERSEY NO.',
 'Unnamed: 3': 'CLUB',
 'Unnamed: 4': 'Position',
 'Unnamed: 5': 'Height',
 'Unnamed: 6': 'Weight',
 'Unnamed: 7': 'NO. OF GAME PLAYED',
 'Unnamed: 8': 'TOTAL SCORE',
 'Unnamed: 9': 'AVR. SCORE PER GAME',
 'Unnamed: 10': 'FOULS',
 'Unnamed: 11': 'TECHNICAL',
 'Unnamed: 12': 'BLOCK',
 'Unnamed: 13': 'TOTAL ASSIST',
 'Unnamed: 14': 'AVR. ASSIST PER GAME',
 'Unnamed: 15': 'TOTAL REBOUND',
 'Unnamed: 16': 'AVR. REBOUND PER GAME',
 'Unnamed: 17': 'STEAL',
 'Unnamed: 18': 'TOTAL TURN OVER',
 'Unnamed: 19': 'AVR. TURNOVER PER GAME',
 'Unnamed: 20': '3 POINTS ATTEMPT',
 'Unnamed: 21': '3 POINTS MADE',
 'Unnamed: 22': '3 PA %',
 'Unnamed: 23': '2 POINT ATTEMPT',
 'Unnamed: 24': '2 POINT MADE',
 'Unnamed: 25': '2 PA %',
 'Unnamed: 26': 'FIELD GOALS ATTEMPT',
 'Unnamed: 27': 'FIELD GOALS MADE',
 'Unnamed: 28': 'FIELD GOAL %',
 'Unnamed: 29': 'FREE THROW ATTEMPT',
 'Unnamed: 30': 'FREE THROW MADE',
 'Unnamed: 31': 'FREE THROW ACCURACY %',
 'Unnamed: 32': 'EFFICIENCY',
 'Unnamed: 33': nan,
 'Unnamed: 34': nan,
 'Unnamed: 35': nan,
 'Unnamed: 36': nan,
 'Unnamed: 37': nan,
 'Unnamed: 38': nan}

In [23]:
player_stats.rename(columns={'Unnamed: 1': 'Player', 'Unnamed: 2': 'Jersey No.'})

,Nepal Basketball League 2019 (NBL) Player Statistics,Player,Jersey No.,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
4,1,Karma Gurung,8,GGIC,Shooting Guard,5'11,86,14,38,2.714286,...,12,6,50,2.071429,75.0,46.0,29.0,14.0,NaN,NaN
5,2,Chiranjivi Rokaya,35,GGIC,Small Forward,5'11,66,14,11,0.785714,...,8,1,12.5,0.571429,22.0,14.0,8.0,14.0,NaN,NaN
6,3,Rajiv Joshi,7,GGIC,Guard,5'10,76,14,112,8,...,22,18,81.818182,8,182.0,70.0,112.0,14.0,NaN,NaN
7,4,Binod Shrestha,3,GGIC,Gaurd,5'8,78,14,116,8.285714,...,6,4,66.666667,5.357143,161.0,86.0,75.0,14.0,NaN,NaN
8,5,Kabindra Pradhan,1,GGIC,Small Forward,6'0,69,14,41,2.928571,...,15,7,46.666667,3.571429,81.0,31.0,50.0,14.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,10,Binesh Neupane,12,RBC,PowerForward,6'0,85,14,24,1.714286,...,4,4,100,0.714286,45.0,35.0,10.0,14.0,NaN,NaN
126,11,Suman Basnet,13,RBC,Center,6'0,72,14,49,3.5,...,11,6,54.545455,4.928571,97.0,28.0,69.0,14.0,NaN,NaN
127,12,Rupak Kunwar,30,RBC,NaN,NaN,NaN,14,48,3.428571,...,8,4,50,0.785714,58.0,47.0,11.0,14.0,NaN,NaN
128,13,Anish Magar,5,RBC,NaN,NaN,NaN,14,47,3.357143,...,3,1,33.333333,2.642857,67.0,30.0,37.0,14.0,NaN,NaN
129,14,Asish Basnet,15,RBC,NaN,NaN,NaN,14,6,0.428571,...,1,1,100,0.214286,8.0,5.0,3.0,14.0,NaN,NaN

In [ ]:
player_stats.to_csv('player_stats_men.csv')